### ISSUE TITLE
Does this project support domin fronting

### ISSUE THREAD

**Issue by JT0cZ7** [RedTeamPentesting/resocks#1]
This project is really awesome!!
And i wanna further know whether it support domain fronting technique by adding host header.

Thanks!

**Comment by rtpt-erikgeiser** [comment]
Thanks for your feedback, we're glad to hear you like `resocks`. This technique does not apply to `resocks` because it does not use HTTPS, only TLS. Fortunately, it does not include the target domain in the TLS SNI. Instead, the public key derived from the connection key is used as SNI.

**Comment by JT0cZ7** [comment]
Oh I get it now~

Frankly speaking, i wanna try this in CDN scene (in order to prevent ip-banned from some firewall strategies) and I will appreciate you if you give me some guidance on how to deploy in this particular scene!

Thanks!

**Comment by rtpt-erikgeiser** [comment]
Unless you find a CDN that allows you to pass a TLS connection as-is without interception to your IP-banned server I don't think this is possible.
